# [default_session]
# startup_command = "nvim"
# path = {}
# windows = [ "lazygit", "test" ]


[[session]]
name = "sesh conf"
path = "~/.local/share/chezmoi/dot_config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.local/share/chezmoi/dot_config/sesh/sesh.toml"

[[window]]
name = "lazygit"
startup_script = "lazygit"

[[window]]
name = "test"
startup_script = ""
